### ISSUE TITLE
.env File

### ISSUE THREAD

**Issue by CipriaNeamtu** [NaYckulB/favorite-cities-05#1]
This file: https://github.com/NaYckulB/favorite-cities-05/blob/f27d5303d3e0426978195a26fba3ed17abaf5b4e/.env#L1
should be secret, if you change the syntax in .gitignore to: ".env", git will ignore that file. Also you should delete the .env file from GitHub.

**Comment by NaYckulB** [comment]
I solved it, thank you Ciprian.
